Refactor renderers
Setono/SyliusCMSPlugin pull request #93
Opened 2022-01-11 21:02 UTC by loevgaard

This PR will change the return type on renderers. This was done to allow to show the toolbar even though elements are cached

2022-01-11 21:16 UTC, loevgaard commented
Sadly I just discovered that it doesn't add nested elements to the element stack: 

![image](https://user-images.githubusercontent.com/2412177/149022757-ad2a8c38-5556-4031-9553-dc45d03a7019.png)

I will have to think about how this can be fixed :|

2022-01-19 07:24 UTC, Roshyo requested changes

2022-01-19 07:24 UTC, Roshyo commented on src/Model/Block.php
> +        return 'block';
Why not using the constants ?

2022-01-19 07:24 UTC, Roshyo commented on src/Model/Carousel.php
> +        return 'carousel';
Why not using the constants ?

2022-01-19 07:24 UTC, Roshyo commented on src/Model/View.php
> +        return 'view';
Why not using the constants ?

2022-01-19 07:24 UTC, Roshyo commented on src/Renderer/ElementId.php
> +    }
Missing the `isPage` method ?

2022-01-19 07:24 UTC, Roshyo commented on src/Resources/views/view/non_existing_template.html.twig
> +    <a href="{{ path('setono_sylius_cms_admin_template_create', {'code': code}) }}">/admin</a> to create this template
Shouldn't this be translated ?

2022-01-19 07:24 UTC, Roshyo commented on src/Stack/ElementStack.php
>      }
missing getPages() method ?

2022-01-19 07:25 UTC, loevgaard commented on src/Model/Block.php
> +        return 'block';
Haha, no idea. Newbie me

2022-01-19 07:25 UTC, loevgaard commented on src/Resources/views/view/non_existing_template.html.twig
> +    <a href="{{ path('setono_sylius_cms_admin_template_create', {'code': code}) }}">/admin</a> to create this template
Yes!

2022-01-19 07:27 UTC, loevgaard commented on src/Stack/ElementStack.php
>      }
I know that `Page` is also an `ElementInterface`, but pages are not added to the element stack, but maybe that would be the consistent thing to do. Right now the element stack is only used by the toolbar

2022-01-31 12:31 UTC, loevgaard commented on src/Renderer/ElementId.php
> +    }
We don't use pages the same way we use the other elements. I will add it when we need or when someone needs it :)

2022-01-31 12:32 UTC, loevgaard commented on src/Stack/ElementStack.php
>      }
Same answer as the other page related question :)

2022-01-31 13:17 UTC, loevgaard commented on src/Resources/views/view/non_existing_template.html.twig
> +    <a href="{{ path('setono_sylius_cms_admin_template_create', {'code': code}) }}">/admin</a> to create this template
These were here before, but I have added todos

2022-01-31 13:31 UTC, merged